### PR TITLE
remove boto2 dependency

### PR DESCRIPTION
**Pull request by jaecktec**
Problem:
having the boto2 dependency makes it more complicated to use e.g. proxies, 
also it is more readable using the named exceptions from boto3 

I've also added boto3 typings

### CODE REVIEW

**Review by bchew — COMMENTED** [review]
@jaecktec thanks for the PR, I'm agreeable with deprecating `boto2` in favour of just having `boto3`. However, I'm not so sure of adding `boto3_type_annotations` as from what I could tell it's no longer maintained (https://github.com/alliefitter/boto3_type_annotations) and the maintainer has pointed to https://github.com/vemel/mypy_boto3_builder.

What do you think of just reducing the scope of changes to just deprecating `boto2` and consolidating to just `boto3`?

**Comment by jaecktec** [comment]
Good point, I will check the other lib

**Comment by jaecktec** [comment]
removed the boto3_type_annotations, are you in for squashing the pr or keep it like this?

**Review by bchew — APPROVED** [review]
@jaecktec i'll just squash and merge, thanks!

**Pull request merged**
