### PR TITLE
Pass only required attributes of LSI's while creating table

### PR DESCRIPTION
**Pull request by DilLip-Chowdary-Codes**
Fixes issues in create_table, when table has local secondary indexes

### CODE REVIEW

**Comment by DilLip-Chowdary-Codes** [comment]
Related Issue #197

**Review by bchew — COMMENTED** [review]
Thanks for the PR @DilLip-Chowdary-Codes! Could you please fix the linting issue (this project uses black) as it's failing CI.

Not required but if you can add a test for this change that would be great too, thanks!

**Comment by DilLip-Chowdary-Codes** [comment]
@bchew I've applied black, and when I run `black --check .`, i got below output:

```
All done! ✨ 🍰 ✨
5 files would be left unchanged.
```

**Comment by bchew** [comment]
> @bchew I've applied black, and when I run `black --check .`, i got below output:
> 
> ```
> All done! ✨ 🍰 ✨
> 5 files would be left unchanged.
> ```

I've just done a check and CI output is valid, perhaps you might not be running the current version of Black as per what's used by this project (there were some changes when Black got upgraded to v23)? You can install all the dev requirements as per https://github.com/bchew/dynamodump#development

**Review by bchew — APPROVED** [review]

**Pull request merged**
