### PR TITLE
Added Flush Parameter

### PR DESCRIPTION
**Pull request by superprat**
Flush Database drops the table and recreates it, easy way to delete all the data

### CODE REVIEW

**Comment by bchew** [comment]
@superprat apologies for taking awhile to check on this. Would rather the parameter be called `empty` rather than `flush` if that's fine with you. Shall merge it after that change if it's agreeable. Thanks!

**Comment by superprat** [comment]
sure! that sounds fine

On Tue, 17 Nov 2015 at 06:18 Benny Chew <notifications@github.com> wrote:
@superprat apologies for taking awhile to check on this. Would rather the parameter be
called empty rather than flush if that's fine with you. Shall merge it after that change if it's agreeable.
Thanks!

**Comment by bchew** [comment]
Cheers, let me know when you've made the changes and I'll check it and get it in.

**Comment by superprat** [comment]
I've updated the name

**Comment by bchew** [comment]
Thanks!

**Pull request merged**
