### PR TITLE
Skip throughput update on restore

### PR DESCRIPTION
**Pull request by charlesknipe**
This corrects the issue where even when passing --skipThroughputUpdate the utility will still attempt to adjust the provisioned capacity of the table during restore.

This is particularly important when working with tables that are configured for On Demand billing, as the throughput updates will not succeed.

### CODE REVIEW

**Comment by iksnae** [comment]
@charlesknipe Thank you so much for submitting this! i'm not sure what's failing on the CI build, but it worked exactly as expected.

**Comment by teamclicker** [comment]
@charlesknipe thanks for this!

**Comment by entropyjx** [comment]
I think CICD is failing due to flake8, some blank lines not following style standards, please check the cicd logs.

**Review by bchew — APPROVED** [review]
Thanks @charlesknipe

**Pull request merged**
