### PR TITLE
Confirm before deleting tables.

### PR DESCRIPTION
**Pull request by adam-operatingops**
@bchew thanks for writing `dynamodump`! Very handy tool. While using it I was surprised by the step that deletes tables (which is the default and you have to know to turn it off), thankfully with no data loss in this case. I think there's some value in adding protection around that.

This adds a confirmation before deleting tables. It also adds a flag to disable confirmations for automated cases (like tests or scripts).

I considered adjusting the CLI args so that the default was to not delete (so the user would have to set an explicit flag to delete), but that was a bigger change to the interface and I thought it was better to keep it small. By adding a confirmation step, the most anyone would have to do is add `--noConfirm` to any automated scripts they have running.

I've exercised this against a table in one of my sandbox AWS accounts and it looks good. Will rely on Travis to run the automated tests.

### CODE REVIEW

**Comment by PaulLiang1** [comment]
same here. 
accidentally remove a global table created in cloudformation, heaps of fun to fix it. 
luckily it was on testing environment..

**Comment by dehli** [comment]
Accidentally deleted a table as well b/c I didn't realize this was the default behavior. This PR would be great!

**Review by bchew — COMMENTED** [review]
@adam-operatingops thanks for the PR and apologies for taking this long to respond - happy to merge this with just the change being applied to Github Actions instead as this repo was moved from Travis CI, and perhaps `six` being upgraded to latest version?

**Comment by adam-operatingops** [comment]
@bchew sounds good, I merged master and moved the build config to GitHub workflows and bumped the `six` version in the merge conflict resolution. Also noticed the readme was out of date and updated it to include the new argument. Can you approve the workflow run so we can see if the changes pass tests?

The lab environment I originally used for this no longer exists, so I haven't rerun my manual tests. I'll be relying on the coverage of the build system to exercise the updates.

**Review by bchew — APPROVED** [review]
Thanks @adam-operatingops!

**Comment by adam-operatingops** [comment]
No problem @bchew, thanks for merging.

**Pull request merged**
