### PR TITLE
Limit thread count, support backup by tags, compressed backups and storage in S3

### PR DESCRIPTION
**Pull request by jrm16020**
Also did some cleanup to quiet `pylint`.  The README is updated with examples of what a backup and restore process would look like using the `-t, --tag` and `-b, --bucket` arguments.  Added boto3 for dynamo table tag support.

### CODE REVIEW

**Comment by bchew** [comment]
@nickchoate thanks for the PR, could you resolve the conflicts and I would look at merging it, cheers!

**Comment by jrm16020** [comment]
Sure thing @bchew .  Rebased my branch and the conflicts are resolved.

**Comment by bchew** [comment]
@jrm16020 awesome additions! :) Just have one minor thing, if you're agreeable to it - alright with you to change all the `'` to `"`? I know it's not a PEP8 thing but just find it neater if everything uses the same type of quotes.. Thanks!

**Comment by jrm16020** [comment]
Thanks @bchew!  I rebased to get the changes from the merged PRs and switched all of the `'` to `"`, at least those outside of comments and in the help messages of argparser.  Let me know if I can do anything else!

**Comment by bchew** [comment]
Thanks @jrm16020! Merging 🚀

**Pull request merged**
