### PR TITLE
Allow dynamodump to be imported as a module

### PR DESCRIPTION
**Pull request by nickchoate**
Refactored main code into a main method to allow importing of dynamodump script into other python scripts.

### CODE REVIEW

**Comment by bchew** [comment]
@nickchoate thanks for the PR, could you resolve the conflicts and I would look at merging it, cheers!

**Comment by nickchoate** [comment]
@bchew Done.  Thanks!

**Comment by angusbayley** [comment]
@nickchoate is there any accompanying documentation for this mode of use?

From a quick glance it appears that when importing this as a module via the `main` method it still relies on all the command line arguments being passed to the parent script that calls this module. Is that the intended behaviour/am I missing something?

**Comment by nickchoate** [comment]
@angusbayley It was primarily done to allow customization to the behavior of Dynamodump.  By adding the code into a main method, it can be run as it is today without change or you can call the individual methods yourself inside another python program.  We had a need to customize the behavior (i.e. we wanted to customize the behavior in main) and by allowing us to effectively import this python file and call the methods to achieve the result.  

A further refactor could be done to extract all the logic into another function with kwargs and let main handle gathering the information from command line if you are happy with the functionality of how main works in general.  

So that's a long way to say, no there's no documentation as to how to use it in this way, as I was assuming at the time, you'd want to fundamentally customize the program (i.e. not use main) if you chose to call it from another program.

**Comment by angusbayley** [comment]
@nickchoate cool - thanks for the reply/explanation!

**Pull request merged**
